version: "3.9"
services:
    app:
        build:
            context: .
        ports:
            - "${APP_PORT:-8000}:80"
        volumes:
            - ".:/var/www/html"

networks:
  default:
    external: true
    name: '${APP_DOCKER_NETWORK}'
